### ISSUE TITLE
Possible to find files only, not files and directories?

### ISSUE THREAD

**Issue by endrebak** [steckerhalter/emacs-fasd#5]
I get both files and directories which can be annoying. How do I get files only?

**Comment by steckerhalter** [comment]
I have added a way to list files only, see https://github.com/steckerhalter/emacs-fasd#usage

If you want to bind it to a key directly (without having to press `M--`) do it so:
```cl
(global-set-key
 (kbd "C-h C-f")
 (lambda () (interactive) (fasd-find-file -1)))
```

**Comment by endrebak** [comment]
Much obliged! 

Ps. I found out about your excellent package through https://github.com/syl20bnr/spacemacs/tree/master/contrib/fasd

**Comment by endrebak** [comment]
Prefixes are kinda hard to do in `evil-emacs`. Would be neat with a layer variable `fasd-standard-search` which could be set to either `-f`, `-d` or `-a`. Would require minimal code-changes, only adding one variable and changing line 72 from:

` (_ " -a "))`

to

`(_  " fasd-standard-search "))`

**Comment by mijoharas** [comment]
:+1:. I'm impressed by your quick turn-around too :smile:

**Comment by steckerhalter** [comment]
I have added a `defcustom` `fasd-standard-search`.

**Comment by mijoharas** [comment]
Hi, First off, thanks for the extension. Secondly, I have a problem with this new feature. I tried to add a function like:
```
(defun fasd-find-file-only ()
  (interactive)
  (fasd-find-file -1))
```
Then invoking with `M-x fasd-find-file-only` (`Fasd Query: .zshrc`) gives me the fasd error screen (I assume, it is the same as `fasd -h` but in a completion mode.

Note, I have what appears to be a working version of fasd-find-directory-only like so:

```
(defun fasd-find-directory-only ()
  (interactive)
  (fasd-find-file 1))
```

so I think the syntax is correct.

**Comment by mijoharas** [comment]
See PR for fix (I think).
