### ISSUE TITLE
fasd conflict with sunrise-commander

### ISSUE THREAD

**Issue by zwb-ict** [steckerhalter/emacs-fasd#7]
I use sunrise-commander, when I run C-x d, I get error:

fasd-add-file-to-db: Wrong type argument: stringp, nil

I have to close global-fasd-mode before I entered sunrise-commander. Is there a better way to resolve this conflict? Thank you!

**Comment by steckerhalter** [comment]
I pushed a fix. Now it should work, please check. Thanks!

**Comment by zwb-ict** [comment]
Perfect! It works very well! Thank you so much!

**Comment by steckerhalter** [comment]
You are very welcome, cheers and have a good day...
