### ISSUE TITLE
Consider using completing-read-function by default

### ISSUE THREAD

**Issue by Wilfred** [steckerhalter/emacs-fasd#9]
This package currently requires grizzl, and users who want other completion engines must configure it. How would you feel about changing the default:

```emacs-lisp
(defcustom fasd-completing-read-function nil
  "The completion function to use for `fasd' completion.
If not set, use `completing-read-function'."
  :type 'symbol)
```

This would mean that the package just works for users of ido, helm and counsel without any additional configuration.

**Comment by steckerhalter** [comment]
I use helm myself. I decided to remove the grizzl dependency altogether and made a PR: https://github.com/steckerhalter/emacs-fasd/pull/10 if you want to have a look...

**Comment by Wilfred** [comment]
Thanks :)

**Comment by steckerhalter** [comment]
My pleasure...
